name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        check:
          - name: Type check
            run: npx tsc --noEmit
          - name: Lint
            run: npx eslint src
          - name: Build
            run: npm run build
          - name: Test (Jest)
            run: npm test
          - name: Test (Cypress)
            run: (npm start & npx wait-on http://127.0.0.1:3000) && NODE_OPTIONS=--openssl-legacy-provider npx cypress run

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          cache: "npm"
      - run: npm ci

      - name: ${{ matrix.check.name }}
        run: ${{ matrix.check.run }}

  Chromatic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          cache: "npm"

      - run: npm ci

      - name: Publish to Chromatic for visual verification
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [CI, Chromatic]
    uses: ./.github/workflows/deploy.yml
